### ISSUE TITLE
Separate the options from the rest of the start command

### ISSUE THREAD

**Issue by mqus** [Edenhofer/minecraft-server#2]
Hi! thank you for providing the script for easily managing a running minecraft server!

I really like the configuration via environment variables. But there is a small thing missing, so here is my request :)

I recently had an `OutOfMemoryError` and wanted to increase the memory that minecraft could take. But for this I had to alter the entire `SERVER_START_CMD`, including the jarfile location and anything else. I would much rather only change the java options with something like `SERVER_JAVA_OPTS` or something like that, and the possibility to manually override the `java` command separately (e.g. for only using a specific jdk with minecraft).

In this case I don't have to worry about being up to date with the other components, should they change in the future.

**Comment by Edenhofer** [comment]
I understand your problem. However, I feel uncomfortable adding an environment variable for anything Java related. The reason for there currently being no dedicated `*JAVA_*` environment variable is because not all flavors of minecraft use Java. For example the minecraft server cuberite is mostly written in C++.

Having said that, there is a way in which you can make use of bash's variable evaluation and use placeholders for non-JAVA related options. Namely there is an environment variable named `MAIN_EXECUTABLE` pointing to the main jar file. You can use this variables within `SERVER_START_CMD` in order to avoid hard-coding the path of the jar file into the `SERVER_START_CMD`. This works because the management script evaluates the environment  variables in a specific order and uses bash double quotes instead of bash single quotes:

https://github.com/Edenhofer/minecraft-server/blob/6663ed4f8a8687786670387c87a75a2ae910b61e/minecraftd.sh.in#L18-L22

While this is not directly used within the shell script anymore, a similar idea is used in the Makefile:

https://github.com/Edenhofer/minecraft-server/blob/6663ed4f8a8687786670387c87a75a2ae910b61e/Makefile#L24-L26

`MAIN_EXECUTABLE` is used in order to avoid having to refer to the location of the jar file. This is to allow the user to change for example the version of the server by pointing `MAIN_EXECUTABLE` to a different location without having to change the `SERVER_START_CMD`.

To make this more user-friendly, I will switch back to using `MAIN_EXECUTABLE` within `SERVER_START_CMD`.

**Comment by mqus** [comment]
I know, I just want another variable just like MAIN_EXECUTABLE for the options and the java binary. Just name them MC_JAVA_OPTS or something, it doesn't have to be that name.

**Comment by Edenhofer** [comment]
As outlined above in great detail, I am against introducing a Java specific option because they do not translate at all to non-Java based flavors of minecraft-servers. To give a concrete example, the cuberite server does not need any Java binary to run and thus does not need any prefix in front of `MAIN_EXECUTABLE`. Furthermore, the cuberite server does not take any of the Java options because it is not written in Java.

I am afraid you have to resort to modifying `SERVER_START_CMD`. If you really want dedicated environment variables for e.g. the JAVA options, you can write a very simple wrapper which assembles `SERVER_START_CMD` from `MC_JAVA_OPTS` and any additional options you can imagine.
